# -*- coding: utf-8 -*-
# Deployment settings for test.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['D:/Marmalade/6.3/s3e/makefile_builder/mkb.py', 'c:/Users/maks/Documents/test/test.mkb', '--default-buildenv=vc11', '--msvc-project', '--deploy-only']
mkb = 'c:/Users/maks/Documents/test/test.mkb'
mkf = ['d:\\marmalade\\6.3\\modules\\iw2d\\iw2d.mkf', 'd:\\marmalade\\6.3\\modules\\iwgx\\iwgx.mkf', 'd:\\marmalade\\6.3\\modules\\iwgeom\\iwgeom.mkf', 'd:\\marmalade\\6.3\\modules\\iwutil\\iwutil.mkf', 'd:\\marmalade\\6.3\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'd:\\marmalade\\6.3\\modules\\third_party\\libpng\\libpng.mkf', 'd:\\marmalade\\6.3\\modules\\third_party\\zlib\\zlib.mkf', 'd:\\marmalade\\6.3\\modules\\iwresmanager\\iwresmanager.mkf', 'd:\\marmalade\\6.3\\modules\\iwgl\\iwgl.mkf', 'd:\\marmalade\\6.3\\modules\\iwgxfont\\iwgxfont.mkf', 'd:\\marmalade\\6.3\\modules\\third_party\\tiniconv\\tiniconv.mkf']

class DeployConfig(object):
    os = ['android']
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/maks/Documents/test\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    os = ['android']
    embed_icf = -1
    name = 'test'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'test'
    long_caption = 'test'
    version = [0, 0, 1]
    config = ['c:/Users/maks/Documents/test/data/app.icf']
    data_dir = 'c:/Users/maks/Documents/test/data'
    iphone_link_lib = []
    linux_ext_lib = []
    android_extra_application_manifest = []
    iphone_link_libdir = []
    android_aliasname = 'superkey'
    android_keypass = 'maksimka023359'
    iphone_link_libdirs = []
    iphone_link_opts = []
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    android_storepass = 'maksimka023359'
    android_extra_manifest = []
    win32_ext_dll = []
    android_so = []
    android_keystore = 'c:/Users/maks/Documents/test/superkey.key'
    osx_ext_dll = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/maks/Documents/test/build_test_vc11/Debug_test_VC11_gcc_x86/test.so',
                   'release' : r'c:/Users/maks/Documents/test/build_test_vc11/Release_test_VC11_gcc_x86/test.so',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/maks/Documents/test/build_test_vc11/Debug_test_VC11_gcc_mips/test.so',
                   'release' : r'c:/Users/maks/Documents/test/build_test_vc11/Release_test_VC11_gcc_mips/test.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/maks/Documents/test/build_test_vc11/Debug_test_VC11_gcc_arm/test.s3e',
                   'release' : r'c:/Users/maks/Documents/test/build_test_vc11/Release_test_VC11_gcc_arm/test.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/maks/Documents/test/build_test_vc11/Debug_test_VC11_gcc_mips/test.so',
                   'release' : r'c:/Users/maks/Documents/test/build_test_vc11/Release_test_VC11_gcc_mips/test.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/maks/Documents/test/build_test_vc11/Debug_test_VC11_gcc_x86_android/test.so',
                   'release' : r'c:/Users/maks/Documents/test/build_test_vc11/Release_test_VC11_gcc_x86_android/test.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/maks/Documents/test/build_test_vc11/Debug_test_VC11_arm/test.s3e',
                   'release' : r'c:/Users/maks/Documents/test/build_test_vc11/Release_test_VC11_arm/test.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/maks/Documents/test/build_test_vc11/Debug_test_VC11_x86/test.s86',
                   'release' : r'c:/Users/maks/Documents/test/build_test_vc11/Release_test_VC11_x86/test.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
